# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: LTA
title-normal: Live Thoughs About {...}
email: contact@lta.io
description: Here I talk about fun things I do
baseurl: '' # the subpath of your site, e.g. /blog
url: "https://blog.lta.io" # the base hostname & protocol for your site
author: Julien 'Lta' BALLET
street_address:
state:
city:
zip_code:
country:
phone: +33 (0)7 68 16 42 96
languages: Ruby, C, C++, Python
skills: System development, Production engineering (DevOps), Ruby on Rails
rates: Discounted rates for OpenSource
workplace: Available worldwide

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/elthariel
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/djlta
linkedin_url: https://www.linkedin.com/in/balletjulien
pinterest_url:
slack_url:
twitter_url: https://twitter.com/find_lta

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: find_lta
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
